version: '3.1'

services:

  # mariadb service
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: <Password>
      MYSQL_DATABASE: <DBname>
      MYSQL_USER: <User>
      MYSQL_PASSWORD: <Password>
    
    volumes: 
        - ./init:/docker-entrypoint-initdb.d

  # adminer service for multiple database
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
