# Creare nella directory del Dockerfile un file index.php

FROM php:7.2-apache
COPY . /var/www/html/
EXPOSE 80

# docker build -t <ImageName> .
# docker run -t -p <HostPort>:80 --name <ContainerName> <ImageName>