version: '3.1'

services:
  <mariadb-ServiceName>:
    image: mariadb
    hostname: <mariadb-ServiceName>
    environment:
      MYSQL_ROOT_PASSWORD: <RootPassword>
      MYSQL_DATABASE: <DBname>
      MYSQL_USER: <User>
      MYSQL_PASSWORD: <UserPassword>
    volumes: 
     - ./sql-scripts:/docker-entrypoint-initdb.d
    container_name: <mariadb-ServiceName>
    restart: always
    
  <phpMyAdmin-Service>:
    depends_on:
     - <mariadb-ServiceName>
    image: phpmyadmin/phpmyadmin
    ports:
     - 8080:80
    environment:
      PMA_HOST: <mariadb-ServiceName>
    container_name: <phpMyAdmin-Service>
    restart: always  

  <notebook-Service>:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
     - TZ=Europe/Rome
    volumes: 
     - ./<path/to/local>:/work/
    ports:
     - 8888:8888
    container_name: <notebook-Service>
    restart: always    
    
    # Creare una cartella <sql-script> contenente gli script SQL nella directory di docker-compose, la cartella attuale verrà montata nella Workdir del container
    

