version: '3.2'

services:
   <MySQL-ServiceName>:
      image: mysql:8.0
      container_name:  <DBname>
      restart: always
      ports:
       - '<MySQLport>:3306'
      environment:
        MYSQL_ROOT_PASSWORD: <RootPassword>
        MYSQL_USER:  <User>
        MYSQL_PASSWORD:  <UserPassword>

   app:
      depends_on:
       -  <MySQL-ServiceName>
      image: phpmyadmin/phpmyadmin
      container_name:  <phpMyAdmin-ServiceName>
      restart: always
      ports:
       - '<phpMyAdminPort>:80'
      environment:
        PMA_HOST:  <MySQL-ServiceName>
