# Sample PHP WEB
FROM php:7.2-apache
# Creare nella directory del Dockerfile un file index.php
COPY . /var/www/html/
EXPOSE 80

$ docker build -t <ImageName> .
$ docker run -t -p <HostPort ex 80>:80 --name <ContainerName> <ImageName>