version: '3.5'
services:
  db:
    image: mysql:5.7
    container_name: wordpress-mysql
    restart: always
    ports:
      - - 3005:3306"
    volumes:
      - ./data/db:/var/lib/mysql:z
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wordpress
      
  phpmyadmin:
    container_name: wordpress-phpmyadmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 3006:80
    environment:
      PMA_HOST: db
    networks:
      - wordpress
      
  wordpress:
    container_name: wordpress-website
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./data/wp-content:/var/www/html/wp-content
    ports:
      - "3007:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - wordpress
networks:
  wordpress:
    name: wordpress
