# Creare nella directory di docker-compose la cartella <php-script> (con lo script index.php) <sql-script> (con gli script sql) e la cartella cartella <jupyter-notebook> (che conterrà tutti i file del notebook)

version: '3.1'

services:
  <MariadbService>:
    image: mariadb
    restart: always
    hostname: <HostName>
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: <Password>
      MYSQL_DATABASE: <DBname>
      MYSQL_USER: <User>
      MYSQL_PASSWORD: <Password>
    volumes: 
     - ./sql-scripts:/docker-entrypoint-initdb.d
    container_name: <MariadbService>
    
  <phpMyAdminService>:
    depends_on:
     - <MariadbService>
    image: phpmyadmin/phpmyadmin
    restart: always
    container_name: <phpMyAdminService>
    restart: always
    ports:
     - 8000:80
    environment:
      PMA_HOST: <MariadbService>

  <PHPservice>:
    image: php:7.2-apache
    restart: always
    volumes:
     - ./php-scripts/:/var/www/html/
    ports:
     - 8500:80
    container_name: <PHPservice>
    
  <JupyterService>:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
     - TZ=Europe/Rome
    ports:
     - 9000:8888
    container_name: <JupyterService>
    volumes:
     - ./jupyter-notebook/:/work
    restart: always
